// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEisooGha5GLN3sbz0loB1v1ODWbC2Fhw',
    appId: '1:563299098397:web:85c0c77ab88ad569e88bf4',
    messagingSenderId: '563299098397',
    projectId: 'innovabank-e6e7e',
    authDomain: 'innovabank-e6e7e.firebaseapp.com',
    storageBucket: 'innovabank-e6e7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7eOmiVB-JPtWg8CQdFSUJoHQQzkJfD0s',
    appId: '1:563299098397:android:7d6fb36bf378b935e88bf4',
    messagingSenderId: '563299098397',
    projectId: 'innovabank-e6e7e',
    storageBucket: 'innovabank-e6e7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs2PAP7WzOX07OsTi-GwOh_vFZ3WrRRGs',
    appId: '1:563299098397:ios:1e7fa39215ee3ff3e88bf4',
    messagingSenderId: '563299098397',
    projectId: 'innovabank-e6e7e',
    storageBucket: 'innovabank-e6e7e.appspot.com',
    iosBundleId: 'com.example.innovabank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs2PAP7WzOX07OsTi-GwOh_vFZ3WrRRGs',
    appId: '1:563299098397:ios:1e7fa39215ee3ff3e88bf4',
    messagingSenderId: '563299098397',
    projectId: 'innovabank-e6e7e',
    storageBucket: 'innovabank-e6e7e.appspot.com',
    iosBundleId: 'com.example.innovabank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEisooGha5GLN3sbz0loB1v1ODWbC2Fhw',
    appId: '1:563299098397:web:c2928a5e386152e1e88bf4',
    messagingSenderId: '563299098397',
    projectId: 'innovabank-e6e7e',
    authDomain: 'innovabank-e6e7e.firebaseapp.com',
    storageBucket: 'innovabank-e6e7e.appspot.com',
  );
}
